### ISSUE TITLE
Support HTCPCP!

### ISSUE THREAD

**Issue by withoutairs** [toofishes/coffee-monitor#12]
http://en.wikipedia.org/wiki/Hyper_Text_Coffee_Pot_Control_Protocol

**Comment by toofishes** [comment]
I actually tried to do this, and I hit hardcoded assumptions in the node.js HTTP parsing stuff about what valid method names were. I can't find the node.js bug right now, but it is definitely known that their parser is too brittle and makes too many assumptions. :(
